name: Playwright RUN
on:
  push:
    branches:
    - 'main'
  pull_request:
    branches:
    - 'main'
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Ensure browsers are installed
      run: python -m playwright install chromium --with-deps
    - name: Run your tests
      env: 
        MONGO_URI: ${{ secrets.MONGO_URI }}
        REFERRAL_CODE: ${{ secrets.REFERRAL_CODE }}
        NUM_LOOP: ${{ secrets.NUM_LOOP }}
      run: python main.py
